### ISSUE TITLE
Tinker lost colors

### ISSUE THREAD

**Issue by Jervi-sir** [laravel/tinker#127]
- Tinker Version: 2.6.1
- Laravel Version: 8.47.0
- PHP Version: 8.0.7
- Psy Shell: v0.10.8 
- Database Driver & Version:

### Description:
 Tinker is not using colors, all the text is white only, this issue happened when I installed a latest version of Laravel ( 8.47.0 ), 
I went to try some oldest versions of Laravel ( 8.46.0 and older ) tinker worked fine,  text was colored fine, 
 what should we do?

### Steps To Reproduce The Issue:
It happens whenever we create a fresh Laravel project with composer

```
composer create-project laravel/laravel .
```

### Samples

<div style="display:grid;">
<div>
<p style="margin-bottom: 0;">cmd</p>
 <img src="https://user-images.githubusercontent.com/54365256/122692250-ddb53880-d22b-11eb-933e-dfa24f96172f.png" width="300px">
 <img src="https://user-images.githubusercontent.com/54365256/122692253-df7efc00-d22b-11eb-9299-42963bad1ad3.png" width="300px">
</div>
<div>

<p style="margin-bottom: 0;">cmder</p>
 <img src="https://user-images.githubusercontent.com/54365256/122692251-de4dcf00-d22b-11eb-8945-2d0150a4ebcd.png" width="300px">
 <img src="https://user-images.githubusercontent.com/54365256/122692255-e0179280-d22b-11eb-9613-53d8312e604e.png" width="300px">
</div>

**Comment by driesvints** [comment]
Please provide a way for us to reproduce this.

**Comment by bobthecow** [comment]
Which PsySH version is working for you, and which is not?

**Comment by Jervi-sir** [comment]
@driesvints, for me it happens when ever I create a fresh Laravel project via composer

**Comment by Jervi-sir** [comment]
@bobthecow, so far Psy Shell v0.10.8, I edited the report, please check it

**Comment by bobthecow** [comment]
What does running `psy\info()` inside tinker output in both cases?

**Comment by driesvints** [comment]
@bobthecow thanks for helping out here 👍

**Comment by Jervi-sir** [comment]
@bobthecow, 
![Untitled](https://user-images.githubusercontent.com/54365256/122843198-cf801e80-d2f6-11eb-831d-ec2e640000d9.png)

**Comment by Jervi-sir** [comment]
@bobthecow,, want to update you,
 I found a file in "vendor/psy/psysh/src/configuration.php" where a line was 
```
const COLOR_MODE_DISABLED = 'disabled';
```
is it a good way to turn it into 'auto' too

**Comment by bobthecow** [comment]
I believe this issue is https://github.com/symfony/symfony/pull/41723, though not for any of the reasons already listed on that issue.

PsySH (and thus Tinker) treats `--ansi` / `--no-ansi` as a three-state pair of options: either you specify explicitly that you want color, or explicitly don't, or the app decides for you.

As of the latest Symfony, the built-in `--ansi` option is defined as "negatable". So if you don't explicitly specify `--ansi`, it acts like you've implicitly specified `--no-ansi`. So [when PsySH tries to figure out whether you want color or not](https://github.com/bobthecow/psysh/blob/6642375cd48dd88d787ce17ff8c91be1e41322e8/src/Configuration.php#L183), the latest Symfony lies and says you don't.

One additional complication, though: _Symfony Console, itself, [doesn't parse those options that way](https://github.com/symfony/console/blob/649730483885ff2ca99ca0560ef0e5f6b03f2ac1/Application.php#L889-L893),_ despite defining them that way. So I'm pretty convinced this is a bug in the default `--ansi` option definition, and we shouldn't be using negatable like this.

Anyway, it looks like that change [will be reverted until Symfony 6.0](https://github.com/symfony/symfony/pull/41723) because it also caused backwards compatibility breaks (as it did for us), so we can fight that fight later 😛 

In the meantime, specifying `--color` or `--ansi` to force the color on should work!

**Comment by driesvints** [comment]
Seems like this is also a result of https://github.com/symfony/symfony/pull/39642? Anyway, thanks for investigating this @bobthecow.

**Comment by GrahamCampbell** [comment]
Cool. So this will be fixed in the next round of patch releases to the symfony console component?

**Comment by driesvints** [comment]
@GrahamCampbell the PR @bobthecow linked to isn't merged yet.

**Comment by niladam** [comment]
Since this is now closed, while i personally think it should be open while we keep track of it and until it gets fixed here's a simple quickfix for people encountering this. Simply run tinker like this:

`php artisan tinker --ansi` - this forces the color output :)

**Comment by codecapsules** [comment]
> @bobthecow,, want to update you,
> I found a file in "vendor/psy/psysh/src/configuration.php" where a line was
> 
> ```
> const COLOR_MODE_DISABLED = 'disabled';
> ```
> 
> is it a good way to turn it into 'auto' too

Thanks work like a charm !

**Comment by bobthecow** [comment]
Wait, are you saying you edited that file in your vendor folder?

**Comment by GrahamCampbell** [comment]
:trollface:

**Comment by boyet007** [comment]
it works @niladam 
Thank you

**Comment by tiagofrancafernandes** [comment]
> @bobthecow,, want to update you, I found a file in "vendor/psy/psysh/src/configuration.php" where a line was
> 
> ```
> const COLOR_MODE_DISABLED = 'disabled';
> ```
> 
> is it a good way to turn it into 'auto' too

Thanks! Some change now (2021)
```sh
vendor/psy/psysh/src/Configuration.php:37
```
