### ISSUE TITLE
Loop only returns the last value if the curly brackets start on a new line

### ISSUE THREAD

**Issue by victorelec14** [laravel/tinker#161]
- Tinker Version: v2.8.1
- Laravel Version: v9.52.3
- PHP Version: 8.1.16
- Database Driver & Version:
--

### Description:

Tinker displays only the last value of a loop if the curly backet starts in new line

### Steps To Reproduce:

```php
$data = [
    "1111",
    "2222",
    "3333",
    "4444",
];
foreach ($data as $pos)
{
    echo $pos . "\n";
}
```

Result:
```
4444
```

Now with the curly backet in the same line of the foreach
```php
$data = [
    "1111",
    "2222",
    "3333",
    "4444",
];
foreach ($data as $pos){
    echo $pos . "\n";
}`
```

Result :
```
1111
2222
3333
4444
```

Thanks

**Comment by driesvints** [comment]
I don't think this is a tinker issue but rather a psysh one. Please try their repo or a support channel, thanks.

**Comment by bobthecow** [comment]
This is expected! (Though I can totally see why you wouldn't expect it).

As a REPL, PsySH evals your code as soon as it can. It doesn't wait for input to be "done". It also doesn't require semicolons if the input is otherwise complete. So when you type:

```php
foreach ($data as $pos)
{
    echo $pos . "\n";
}
```

… you're really saying:

```php
foreach ($data as $pos);
{
    echo $pos . "\n";
}
```

The difference is subtle :) 

The reason it outputs the final `$pos` is that the loop iteration variable leaks out of the loop scope and the final value is available after the loop completes. To top it all off, your echo is surrounded by brackets but you can just … put brackets wherever you want in PHP. In this case they do nothing interesting at all. So your whole thing is equivalent to:

```php
$data = [
    "1111",
    "2222",
    "3333",
    "4444",
];
$pos = end($data);
echo $pos . "\n";
```

To avoid this, you can:

1. Change your style, and always put opening brackets on the same line while using the REPL. This is my personal preference, as it avoids other, similar sorts of issues.
2. Force line continuation by adding a `\` at the end of the line (much like in Bash or other shells, which also execute as soon as they have valid input).
3. Or disable automatic semicolon insertion, via the `requireSemicolons` config option. This means PsySH _will never_ execute anything until you've added all the semicolons, which can be a bit annoying, but it also prevents your issue here completely.

**Comment by bobthecow** [comment]
Note that this behavior only applies to line-by-line input. Inside another scope that already keeps the input buffer open (e.g. inside a function or class definition, or a namespace block) it will act like you expected, because treating the `foreach` on its own line as a complete statement and executing it won't work inside another block.

It also doesn't apply to pasted input, input from STDIN, or input from the `edit` command.

**Comment by driesvints** [comment]
@bobthecow thanks a lot for that thorough explanation 👍
