### ISSUE TITLE
Suggestion: Multiple line support

### ISSUE THREAD

**Issue by securit** [laravel/tinker#24]
It would be fantastic if tinker supported multiple line statements... because then you could just cut and paste from your code rather than having to remove newline chars before pasting... for example
rather than this:
```
$d=DeviceCamera::with(['device'=>function($query){$query->select('devices.id as device_id', 'name as camera_name', 'slug as webcam_name')->groupBy('devices.id');},'device.device'=>function($query){$query->select('id','id as camera_id', 'camera_lens_type_id', 'settings',DB::raw("cast(settings->>'viewport_order' as int) as viewport_order"))->groupBy('id');},'deployments'=>function($query){$query->select('deployments.id as deployment_id','vessel_id')->groupBy('vessel_id')->groupBy('deployments.id');},'videos'=>function($query){$query->select('videos.id as video_id','server_id as vid_server_id',DB::raw("max(video_duration) as video_duration"),DB::raw('max(size) as size'),DB::raw('min(video_start_timestamp) as video_start_timestamp'),DB::raw('max(video_end_timestamp) as video_end_timestamp'),DB::raw('(array_agg(video_path))[1] as video_path'),'video_name')->groupBy('server_id')->groupBy('video_name');},'videos.server.device'=>function($query){$query->select('id as server_id',DB::raw("(array_agg(settings->>'fqdn'))[1] as fqdn"),DB::raw("(array_agg(settings->>'rtmp_path'))[1] as rtmp_path"));}])->get();
```
I could have this
```
$d = DeviceCamera::with([
    'device'  => function ($query) {
        $query->select(
            'devices.id as device_id', 'name as camera_name', 'slug as webcam_name'
        )->groupBy('devices.id');
    },
    'device.device' => function ($query) {
        $query->select(
            'id', 'id as camera_id', 'camera_lens_type_id', 'settings',
            DB::raw("cast(settings->>'viewport_order' as int) as viewport_order")
        )->groupBy('id');
    },
    'deployments' => function ($query) {
        $query->select(
            'deployments.id as deployment_id', 'vessel_id'
        )->groupBy('vessel_id')->groupBy('deployments.id');
    },
    'videos' => function ($query) {
        $query->select(
            'videos.id as video_id',
            'server_id as vid_server_id',
            DB::raw("max(video_duration) as video_duration"),
            DB::raw('max(size) as size'),
            DB::raw('min(video_start_timestamp) as video_start_timestamp'),
            DB::raw('max(video_end_timestamp) as video_end_timestamp'),
            DB::raw('(array_agg(video_path))[1] as video_path'),
            'video_name'
        )->groupBy('server_id')->groupBy('video_name');
    },
    'videos.server.device' => function ($query) {
        $query->select(
            'id as server_id',
            DB::raw("(array_agg(settings->>'fqdn'))[1] as fqdn"),
            DB::raw("(array_agg(settings->>'rtmp_path'))[1] as rtmp_path")
        );
    }])->get();
```

**Comment by bobthecow** [comment]
Tinker does support multi-line statements.

**Comment by GrahamCampbell** [comment]
:)

**Comment by securit** [comment]
Nope I always need to remove linebreaks.

**Comment by bobthecow** [comment]
Ahhhh. It lets you paste the first few lines 😄 

Trailing commas in function calls, though.

I just pushed a fix to the `develop` branch on PsySH. Do you mind checking that out and confirming that it fixes your issue?

**Comment by securit** [comment]
Hi Justin,

a line ending in “)” followed on the next line by a “->” failed.
"...             ])
RuntimeException with message 'A facade root has not been set.'
>>>                 ->whereHas('device.deployments', function ($query) use ($vessel_id, $start, $end) {
PHP Parse error: Syntax error, unexpected T_OBJECT_OPERATOR on line 1
>>>                     $query->where([
...                         ['vessel_id', '=', $vessel_id],
...                         ['deployment_start_ts', '<=', $end],
...                         ['deployment_end_ts', '>=', $start],
...                     ]);
PHP error:  Undefined variable: query on line 3
“
Once I got rid of the new line at the end of the line, I got 
>>> $d = DeviceCamera::select('id', 'id as camera_id', 'camera_lens_type_id', 'settings',
...                 DB::raw("cast(device_cameras.settings->>'viewport_order' as int) as viewport_order"))->with([
...                 'device'               => function ($query) {
...                     $query->select('devices.id', 'devices.device_id', 'name as camera_name', 'slug as webcam_name');
...                 },
...                 'device.deployments'   => function ($query) {
...                     $query->select('id', 'vessel_id', 'device_id');
...                 },
...                 'videos'               => function ($query) use ($start, $end) {
...                     $query->select('videos.id as video_id', 'vessel_id', 'video_name', 'video_duration', 'size', 'video_start_timestamp', 'video_end_timestamp', 'video_path',
...                         'server_id');
...                 },
...                 'videos.server'        => function ($query) {
...                     $query->select('id', 'device_id', 'device_type_id', 'device_type');
...                 },
...                 'videos.server.device' => function ($query) {
...                     $query->select('id', DB::raw("settings->>'fqdn'[1] as fqdn"), DB::raw("settings->>'rtmp_path'[1] as rtmp_path"));
...                 },
...             ])->whereHas('device.deployments', function ($query) use ($vessel_id, $start, $end) {
...                 $query->where([
...                     ['vessel_id', '=', $vessel_id],
...                     ['deployment_start_ts', '<=', $end],
...                     ['deployment_end_ts', '>=', $start],
...                 ]);
...             })->whereHas('videos', function ($query) use ($vessel_id, $start, $end) {
...                 $query->where([
...                     ['vessel_id', '=', $vessel_id],
...                     ['videos.active', '=', true],
...                     ['video_duration', '>', 0],
...                     ['video_start_timestamp', '<=', $end],
...                     ['video_end_timestamp', '>=', $start],
...                 ]);
...             })->orderBy('id', 'desc')->limit(2)->get();
RuntimeException with message 'A facade root has not been set.'

**Comment by bobthecow** [comment]
Hmm. You're getting into places that PsySH / tinker can't help you as much :)

By default PsySH doesn't require semicolons to execute code, as long as the code is syntactically complete, valid PHP. In your case, the line before `->whereHas` is a valid and complete statement, so PsySH just goes for it.

If you were typing this in yourself, you wouldn't be super surprised to see that this happened, and you could just use `$_->whereHas` to use the return value of the last line to keep going. But in this case, you're pasting and can't adapt on the fly. Unfortunately, with PHP's libedit implementation, I don't believe it's possible to completely solve for paste.

There is this awesome thing called "bracketed paste" that might help here. It makes pasting into readline much saner. _If_ you're using PHP-with-readline, _and_ your terminal app supports it, _and_ the stars align just right :)

Unfortunately it often doesn't work, and when it doesn't it spews escape codes all over the place, so it's not going to be enabled by default, at least for now.

**So you have a couple of options:**

1. Download the latest dev branch and add `"useBracketedPaste" => true` to your PsySH config.

2. If that doesn't work, and you're using PHP with readline (not libedit)… update your `.inputrc` to tell readline you like to paste:

       set enable-bracketed-paste on


**If neither of those work:**

1. Switch your coding style to end lines with `->` instead of starting the next line. This will keep a given line from being syntactically complete, and will keep the input buffer open.

2. Add slashes to the end of ambiguous lines like this to keep them from executing. In PsySH, if you end a line in `\`, it forces it to keep the input going on the next line. This is kind of a pain, but maybe not as much as removing all the newlines? 

3. Disable implicit semicolon support. Add `"requireSemicolons" => true` to your PsySH config. This will keep pastes from executing as soon as you've finished a syntactically complete line. Unfortunately, this is a global setting, so if you change it, you'll have to type `1 + 1;` to get `1 + 1` to get things to execute the rest of the time. 

4. Switch to a PHP with readline instead of libedit and use bracketed paste!

**Comment by DanRibbens** [comment]
Came here trying to figure out the same issue. Instead of changing terminal input behaviour I decided to add a macro for copying joined lines. With this I can select a block of code, press the hotkey assigned to the macro, then paste in the terminal.

In PHPStorm it looks like this:
![image](https://user-images.githubusercontent.com/6434612/50547779-b5c25c80-0c0e-11e9-9a87-d293158d9dc4.png)

**Comment by securit** [comment]
Hi Dan
how did you set that up in PHPstorm?

Thanks
Greg

**Comment by DanRibbens** [comment]
@securit  To set up the macro?
Preselect a block of text in your editor like a query (doesn't matter for just setting it up)
Edit -> Macros -> Start Recording
Edit -> Join Lines
Edit -> Copy
Edit -> Undo
Edit -> Macross -> Stop Recording
Give it a name to save it

Then set it a hotkey in your keymap settings:
![image](https://user-images.githubusercontent.com/6434612/50836730-ecdbf080-1327-11e9-930c-e71814813d3d.png)

Now to use the macro you just highlight everything you want to toss in to tinker and hit your new hotkey.

**Comment by abdelaziz321** [comment]
Same idea of @DanRibbens  but With **Atom**:
we can select multiple lines and join them as one line using **`ctrl + j`**

**Comment by AleksandarSavic95** [comment]
Thanks to @DanRibbens for his genius idea! 🙂 🎉 
In PhpStorm, `join lines` command has a default shortcut - `CTRL + SHIFT + J` (on a mac it looks like this: `^ + ⬆️ + J` ).

**Comment by mufeel** [comment]
within your tinker session type the keyword "edit" which would open an editor to write your code. Once your done exit out and the code will execute. You will be able to see the output
